services:
  guzzle.http.client:
    class:     GuzzleHttp\Client

  exchange.rates.api.factory:
    class:     Commissions\CalculatorContext\Infrastructure\ExchangeRates\ExchangeRatesApiFactory

  exchange.rates.retriever:
    class:     Commissions\CalculatorContext\Infrastructure\ExchangeRates\ExchangeRatesRetriever
    arguments:
      - '@guzzle.http.client'
      - '@exchange.rates.api.factory'

  transactions.data.retriever:
    class:     Commissions\CalculatorContext\Infrastructure\InputData\TransactionsDataRetrieverCSV

  currency.base:
    class:     Brick\Money\Currency
    factory:   [Brick\Money\Currency, of]
    arguments: ['EUR']

  money.private.withdrawal.rule.threshold.amount:
    class:     Brick\Money\Money
    factory:   [Brick\Money\Money, of]
    arguments: ['1000', 'EUR']

  transaction.type.deposit:
    class:     Commissions\CalculatorContext\Domain\ValueObject\TransactionType
    factory:   [Commissions\CalculatorContext\Domain\ValueObject\TransactionType, of]
    arguments: ['deposit']

  transaction.type.withdraw:
    class:     Commissions\CalculatorContext\Domain\ValueObject\TransactionType
    factory:   [Commissions\CalculatorContext\Domain\ValueObject\TransactionType, of]
    arguments: ['withdraw']

  user.type.business:
    class:     Commissions\CalculatorContext\Domain\ValueObject\UserType
    factory:   [Commissions\CalculatorContext\Domain\ValueObject\UserType, of]
    arguments: ['business']

  user.type.private:
    class:     Commissions\CalculatorContext\Domain\ValueObject\UserType
    factory:   [Commissions\CalculatorContext\Domain\ValueObject\UserType, of]
    arguments: ['private']

  condition.common.deposit.rule:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\RuleCondition\ConditionTransactionTypeAndUserType
    arguments:
      - '@transaction.type.deposit'
      - null

  common.deposit.rule:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\CommonDepositRule
    arguments:
      - '@condition.common.deposit.rule'
      - '@currency.base'
      - '0.0003'

  condition.business.withdraw.rule:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\RuleCondition\ConditionTransactionTypeAndUserType
    arguments:
      - '@transaction.type.withdraw'
      - '@user.type.business'

  business.withdraw.rule:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\BusinessWithdrawRule
    arguments:
      - '@condition.business.withdraw.rule'
      - '@currency.base'
      - '0.005'

  condition.private.withdraw.rule:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\RuleCondition\ConditionTransactionTypeAndUserType
    arguments:
      - '@transaction.type.withdraw'
      - '@user.type.private'
      -
#  private.withdraw.rule:
#    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\PrivateWithdrawRule
#    arguments:
#      - '@condition.private.withdraw.rule'
#      - '@currency.base'
#      - '0'
#      - '@money.private.withdrawal.rule.threshold.amount'
#      - '3'
#      - '0.003'

  private.withdraw.rule:
      class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\WeeklyThresholdRule
      arguments:
        - '@condition.private.withdraw.rule'
        - '@transaction.type.withdraw'
        - '@currency.base'
        - '0'
        - '@money.private.withdrawal.rule.threshold.amount'
        - '3'
        - '0.003'

  rules.sequence:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\Rules\RulesSequence
    arguments:
      - ['@common.deposit.rule', '@business.withdraw.rule', '@private.withdraw.rule']

  usercalculationstate.repository.default:
    class:     Commissions\CalculatorContext\Domain\Repository\CommissionsCalculator\UserCalculationStateRepositoryDefault

  commission.calculator:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\CommissionCalculator
    arguments:
      - '@rules.sequence'
      - '@usercalculationstate.repository.default'

  commissions.calculator:
    class:     Commissions\CalculatorContext\Domain\Service\CommissionsCalculator\CommissionsCalculator
    arguments:
      - '@commission.calculator'
